import fs from 'fs';

let content = fs.readFileSync('db/seed-world.js', 'utf-8');

const injectedString = `  { "code": "ikan_bakar", "name": "Ikan Bakar", "description": "Ikan segar yang dibakar sempurna.", "category": "food", "rarity": "common", "equip_slot": null, "buy_price": 40, "sell_price": 20, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 2, "metadata": { "usable": { "heal_hp": 20 }, "crafting": { "materials": { "common_fish": 1, "wood": 1 } } } },
  { "code": "sup_belut", "name": "Sup Belut Penambah Stamina", "description": "Sup hangat yang membakar semangatmu.", "category": "food", "rarity": "rare", "equip_slot": null, "buy_price": 100, "sell_price": 50, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 2, "metadata": { "usable": { "heal_stamina": 25 }, "crafting": { "materials": { "serpent_eel": 1, "herb": 1 } } } },
  { "code": "ramuan_penyembuh", "name": "Ramuan Penyembuh", "description": "Cairan merah berbau herbal pekat.", "category": "potion", "rarity": "uncommon", "equip_slot": null, "buy_price": 80, "sell_price": 40, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 1, "metadata": { "usable": { "heal_hp": 50 }, "crafting": { "materials": { "treant_sap": 1, "herb": 2 } } } },
  { "code": "elixir_bulan", "name": "Elixir Bulan", "description": "Memancarkan cahaya biru lembut, memulihkan Mana.", "category": "potion", "rarity": "rare", "equip_slot": null, "buy_price": 150, "sell_price": 75, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 1, "metadata": { "usable": { "heal_mp": 50 }, "crafting": { "materials": { "moonpetal": 1, "cave_moss": 2 } } } },
  { "code": "telur_dadar", "name": "Telur Dadar Liar", "description": "Makanan sederhana namun mengenyangkan.", "category": "food", "rarity": "common", "equip_slot": null, "buy_price": 30, "sell_price": 15, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 2, "metadata": { "usable": { "heal_hp": 15 }, "crafting": { "materials": { "duck_egg": 1, "wood": 1 } } } },
  { "code": "mantel_bulu", "name": "Mantel Bulu Kelinci", "description": "Pakaian hangat dan ringan.", "category": "armor", "rarity": "common", "equip_slot": "body", "buy_price": 200, "sell_price": 100, "stackable": 0, "max_stack": 1, "tradeable": 1, "weight": 5, "metadata": { "stats": { "defense": 5 }, "crafting": { "materials": { "rabbit_fur": 3, "iron_ore": 1 } } } },

  { "code": "salad_buah", "name": "Salad Buah Hutan", "description": "Campuran Beri Liar dan Pisang yang menyegarkan.", "category": "food", "rarity": "common", "equip_slot": null, "buy_price": 60, "sell_price": 30, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 2, "metadata": { "usable": { "heal_hp": 40 }, "crafting": { "materials": { "wild_berries": 2, "banana": 1 } } } },
  { "code": "kue_manis", "name": "Kue Manis", "description": "Roti panggang dengan gula dan telur.", "category": "food", "rarity": "uncommon", "equip_slot": null, "buy_price": 120, "sell_price": 60, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 2, "metadata": { "usable": { "heal_hp": 30, "heal_stamina": 20 }, "crafting": { "materials": { "sugar": 1, "wheat": 2, "duck_egg": 1 } } } },
  { "code": "ramuan_nyawa_hitam", "name": "Ramuan Nyawa Hitam", "description": "Ramuan kental dari Lotus Hitam dan Darah Lintah.", "category": "potion", "rarity": "epic", "equip_slot": null, "buy_price": 500, "sell_price": 250, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 1, "metadata": { "usable": { "heal_hp": 150 }, "crafting": { "materials": { "black_lotus": 1, "leech_blood": 3 } } } },
  { "code": "esensi_salju_abadi", "name": "Esensi Salju Abadi", "description": "Dingin yang membekukan jiwa, namun memulihkan mana.", "category": "potion", "rarity": "epic", "equip_slot": null, "buy_price": 600, "sell_price": 300, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 1, "metadata": { "usable": { "heal_mp": 100 }, "crafting": { "materials": { "frost_crystal": 1, "ice_melon": 2 } } } },
  { "code": "sate_paha_katak", "name": "Sate Paha Katak", "description": "Daging kenyal hasil panggangan.", "category": "food", "rarity": "common", "equip_slot": null, "buy_price": 50, "sell_price": 25, "stackable": 1, "max_stack": 99, "tradeable": 1, "weight": 3, "metadata": { "usable": { "heal_hp": 35 }, "crafting": { "materials": { "giant_frog_leg": 1, "wood": 1 } } } },
  { "code": "jubah_yeti", "name": "Jubah Yeti Tahan Dingin", "description": "Jubah tebal dari bulu Yeti asli.", "category": "armor", "rarity": "rare", "equip_slot": "body", "buy_price": 800, "sell_price": 400, "stackable": 0, "max_stack": 1, "tradeable": 1, "weight": 8, "metadata": { "stats": { "defense": 15, "hp": 50 }, "crafting": { "materials": { "yeti_fur": 3, "seal_oil": 1 } } } },
  { "code": "zirah_naga_rawa", "name": "Zirah Sisik Hydra", "description": "Baju besi yang tahan korosi dan sangat kuat.", "category": "armor", "rarity": "epic", "equip_slot": "body", "buy_price": 1500, "sell_price": 750, "stackable": 0, "max_stack": 1, "tradeable": 1, "weight": 12, "metadata": { "stats": { "defense": 25, "mp": 20 }, "crafting": { "materials": { "hydra_scale": 5, "swamp_gas_vial": 2, "iron_ore": 3 } } } },
  { "code": "mahkota_griffin", "name": "Mahkota Griffin", "description": "Hiasan kepala lambang kebebasan.", "category": "armor", "rarity": "rare", "equip_slot": "head", "buy_price": 700, "sell_price": 350, "stackable": 0, "max_stack": 1, "tradeable": 1, "weight": 2, "metadata": { "stats": { "defense": 10, "speed": 15 }, "crafting": { "materials": { "griffin_claw": 2, "harpy_feather": 3 } } } },
  { "code": "kalung_tengkorak", "name": "Kalung Tengkorak Goblin", "description": "Menakutkan tapi berkhasiat sihir.", "category": "accessory", "rarity": "uncommon", "equip_slot": "accessory", "buy_price": 300, "sell_price": 150, "stackable": 0, "max_stack": 1, "tradeable": 1, "weight": 1, "metadata": { "stats": { "attack": 5 }, "crafting": { "materials": { "goblin_ear": 5, "reeds": 2 } } } },`;

// Cari di teks, hapus
let newContent = content.replace(injectedString, "");

// Masukkan ke akhir WORLD_ITEMS
newContent = newContent.replace(/(?=\];\n\nexport const GEMSTONE_ENCHANTS)/, "\n" + injectedString + "\n");

fs.writeFileSync('db/seed-world.js', newContent, 'utf-8');
console.log("Fixed manually!");
